# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\screengif\ui\recording.ui'
#
# Created: Wed Apr 03 15:22:30 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_RecordingDialog(object):
    def setupUi(self, RecordingDialog):
        RecordingDialog.setObjectName(_fromUtf8("RecordingDialog"))
        RecordingDialog.resize(574, 385)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RecordingDialog.sizePolicy().hasHeightForWidth())
        RecordingDialog.setSizePolicy(sizePolicy)
        RecordingDialog.setSizeGripEnabled(False)
        self.horizontalLayout = QtGui.QHBoxLayout(RecordingDialog)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_4 = QtGui.QLabel(RecordingDialog)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.spinFps = QtGui.QSpinBox(RecordingDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinFps.sizePolicy().hasHeightForWidth())
        self.spinFps.setSizePolicy(sizePolicy)
        self.spinFps.setMinimum(1)
        self.spinFps.setProperty("value", 10)
        self.spinFps.setObjectName(_fromUtf8("spinFps"))
        self.horizontalLayout_6.addWidget(self.spinFps)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_5 = QtGui.QLabel(RecordingDialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_7.addWidget(self.label_5)
        self.spinOutWidth = QtGui.QSpinBox(RecordingDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinOutWidth.sizePolicy().hasHeightForWidth())
        self.spinOutWidth.setSizePolicy(sizePolicy)
        self.spinOutWidth.setMaximum(1024)
        self.spinOutWidth.setProperty("value", 128)
        self.spinOutWidth.setObjectName(_fromUtf8("spinOutWidth"))
        self.horizontalLayout_7.addWidget(self.spinOutWidth)
        self.label_6 = QtGui.QLabel(RecordingDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_7.addWidget(self.label_6)
        self.spinOutHeight = QtGui.QSpinBox(RecordingDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinOutHeight.sizePolicy().hasHeightForWidth())
        self.spinOutHeight.setSizePolicy(sizePolicy)
        self.spinOutHeight.setMaximum(1024)
        self.spinOutHeight.setProperty("value", 128)
        self.spinOutHeight.setObjectName(_fromUtf8("spinOutHeight"))
        self.horizontalLayout_7.addWidget(self.spinOutHeight)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.butRecord = QtGui.QPushButton(RecordingDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butRecord.sizePolicy().hasHeightForWidth())
        self.butRecord.setSizePolicy(sizePolicy)
        self.butRecord.setCheckable(True)
        self.butRecord.setObjectName(_fromUtf8("butRecord"))
        self.verticalLayout_3.addWidget(self.butRecord)
        self.line = QtGui.QFrame(RecordingDialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_3.addWidget(self.line)
        self.butSaveGif = QtGui.QPushButton(RecordingDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butSaveGif.sizePolicy().hasHeightForWidth())
        self.butSaveGif.setSizePolicy(sizePolicy)
        self.butSaveGif.setObjectName(_fromUtf8("butSaveGif"))
        self.verticalLayout_3.addWidget(self.butSaveGif)
        self.butSaveSequence = QtGui.QPushButton(RecordingDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butSaveSequence.sizePolicy().hasHeightForWidth())
        self.butSaveSequence.setSizePolicy(sizePolicy)
        self.butSaveSequence.setObjectName(_fromUtf8("butSaveSequence"))
        self.verticalLayout_3.addWidget(self.butSaveSequence)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.butPlay = QtGui.QPushButton(RecordingDialog)
        self.butPlay.setCheckable(True)
        self.butPlay.setObjectName(_fromUtf8("butPlay"))
        self.verticalLayout_2.addWidget(self.butPlay)
        self.playbackSlider = QtGui.QSlider(RecordingDialog)
        self.playbackSlider.setMaximum(0)
        self.playbackSlider.setOrientation(QtCore.Qt.Horizontal)
        self.playbackSlider.setTickInterval(0)
        self.playbackSlider.setObjectName(_fromUtf8("playbackSlider"))
        self.verticalLayout_2.addWidget(self.playbackSlider)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.previewImage = QPixmapWidget(RecordingDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previewImage.sizePolicy().hasHeightForWidth())
        self.previewImage.setSizePolicy(sizePolicy)
        self.previewImage.setObjectName(_fromUtf8("previewImage"))
        self.verticalLayout.addWidget(self.previewImage)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(RecordingDialog)
        QtCore.QMetaObject.connectSlotsByName(RecordingDialog)

    def retranslateUi(self, RecordingDialog):
        RecordingDialog.setWindowTitle(_translate("RecordingDialog", "Dialog", None))
        self.label_4.setText(_translate("RecordingDialog", "Sample rate (fps)", None))
        self.label_5.setText(_translate("RecordingDialog", "Output size", None))
        self.label_6.setText(_translate("RecordingDialog", "x", None))
        self.butRecord.setText(_translate("RecordingDialog", "Record", None))
        self.butSaveGif.setText(_translate("RecordingDialog", "Save GIF", None))
        self.butSaveSequence.setText(_translate("RecordingDialog", "Save image sequence", None))
        self.butPlay.setText(_translate("RecordingDialog", "Play", None))

from screengif.pixmap_widget import QPixmapWidget
